#!/bin/bash

lftp -c "open ftp.redhat.com ; ls /redhat/linux/enterprise/4/en/os/x86_64/SRPMS" > 4-en-os-x86_64-SRPMS.txt
lftp -c "open ftp.redhat.com ; ls /redhat/linux/enterprise/5Server/en/os/SRPMS" > 5Server-en-os-SRPMS.txt
lftp -c "open ftp.redhat.com ; ls /redhat/linux/enterprise/6Server/en/os/SRPMS" > 6Server-en-os-SRPMS.txt

